name: flutter_apps
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_native_splash: ^1.2.1 # Added for splash screen
  page_transition: "^2.0.0" # Added for Page Transition Animation
  font_awesome_flutter: ^9.1.0 # Added for icons
  fancy_bar: ^2.0.0
  bottom_navy_bar: ^6.0.0
  dots_indicator: ^2.0.0
  animated_text_kit: ^4.2.1
  custom_picker: ^0.0.4
  carousel_slider: ^4.0.0
  fancy_drawer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.1"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/artklub_icon.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  fonts:
    - family: Sail
      fonts:
        - asset: assets/fonts/Sail-Regular.ttf

    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Bold.ttf

        - asset: assets/fonts/Quicksand-Light.ttf

        - asset: assets/fonts/Quicksand-Medium.ttf

        - asset: assets/fonts/Quicksand-Regular.ttf

        - asset: assets/fonts/Quicksand-SemiBold.ttf


    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
        - asset: assets/fonts/Roboto-BlackItalic.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-BoldItalic.ttf
        - asset: assets/fonts/Roboto-Italic.ttf
        - asset: assets/fonts/Roboto-Light.ttf
        - asset: assets/fonts/Roboto-LightItalic.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
        - asset: assets/fonts/Roboto-MediumItalic.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Thin.ttf
        - asset: assets/fonts/Roboto-ThinItalic.ttf


    # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
